# This is a basic workflow to help you get started with Actions

name: Blue/Green Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: hello
        run: echo Hello, world!
        
      - name: Docker Build and Upload to AWS ECR
        # You may pin to the exact commit or the version.
        # uses: vitr/actions-build-and-upload-to-ecs@7e2d171297db18c0013e04944e880b473ba39bed
        uses: vitr/actions-build-and-upload-to-ecs@v1.0.0
        with:
          # The AWS access key id
          access_key_id: ${{SECRETS.ACCESS_KEY_ID}}
          # The AWS secret access key
          secret_access_key: ${{SECRETS.ACCESS_KEY_SECRET}}
          # AWS Account ID
          account_id: ${{SECRETS.ACCOUNT_ID}}
          # Name of your ECR repository
          repo: blue-green-depl-repo
          # The AWS region
          region: ${{SECRETS.REGION}}
          # Set this to true to create the repository if it does not already exist
          create_repo: true
          # Comma-separated string of ECR image tags
          tags: "v1"
      
